services:
  db:
    image: postgres:16
    container_name: datapulse_db
    environment:
      POSTGRES_USER: datapulse
      POSTGRES_PASSWORD: datapulse
      POSTGRES_DB: datapulse
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: datapulse_api
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+asyncpg://datapulse:datapulse@db:5432/datapulse
    depends_on:
      - db

volumes:
  postgres_data: