"""add insight to pipeline_runs

Revision ID: 28d5e76d5097
Revises: 9889bcb7f508
Create Date: 2026-08-31 17:34:00.717932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d5e76d5097'
down_revision: Union[str, Sequence[str], None] = '9889bcb7f508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('insight', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'insight')
    # ### end Alembic commands ###
