"""create hospital_infections table

Revision ID: 45b986f4c750
Revises: 8ba781dfe17d
Create Date: 2026-08-24 18:19:30.047919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b986f4c750'
down_revision: Union[str, Sequence[str], None] = '8ba781dfe17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_infections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('measure_id', sa.String(), nullable=False),
    sa.Column('measure_name', sa.String(), nullable=False),
    sa.Column('compared_to_national', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['hospitals.facility_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('hospitals_name_trgm'), 'hospitals', ['facility_name'], unique=False, postgresql_ops={'facility_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('hospitals', 'telephone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('hospital_infections')
    # ### end Alembic commands ###
