"""add telephone_number to hospitals

Revision ID: 8579784dae8b
Revises: ff3da8a6a110
Create Date: 2026-08-24 12:47:36.120607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8579784dae8b'
down_revision: Union[str, Sequence[str], None] = 'ff3da8a6a110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('telephone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'telephone_number')
    # ### end Alembic commands ###
