"""add avg_rating to pipeline_runs

Revision ID: 9889bcb7f508
Revises: 45b986f4c750
Create Date: 2026-08-31 15:43:42.128798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9889bcb7f508'
down_revision: Union[str, Sequence[str], None] = '45b986f4c750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('avg_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'avg_rating')
    # ### end Alembic commands ###
