"""create hospitals table

Revision ID: fa6ad934ab9f
Revises: 
Create Date: 2026-08-18 16:46:05.680668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6ad934ab9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('hospital_type', sa.String(), nullable=False),
    sa.Column('hospital_ownership', sa.String(), nullable=False),
    sa.Column('emergency_services', sa.String(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('facility_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospitals')
    # ### end Alembic commands ###
